services:
  db:
    image: postgis/postgis:14-3.2
    container_name: conflict_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Flnqrt5&78$%"
      POSTGRES_DB: geo_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  db-seed:
    build:
      context: ./db-seed
      dockerfile: Dockerfile
    container_name: conflict_db_seed
    volumes:
      - ./db-seed:/app
      - ./datasets:/datasets  # Mount local datasets directory
    environment:
      PGUSER: postgres
      PGPASSWORD: "Flnqrt5&78$%"
      PGDATABASE: geo_db
      PGHOST: db
      PGPORT: 5432
    depends_on:
      - db
    # We won't start db-seed automatically on `docker-compose up`
    # We'll run it manually with `docker-compose run db-seed bash -c "/app/seed_conflict_data.sh"`

  backend:
    build: ./backend
    container_name: conflict_backend
    ports:
      - "4000:4000"
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=Flnqrt5&78$%
      - PGDATABASE=geo_db
      - PGPORT=5432
      - PORT=4000
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: conflict_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
      - martin
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  # Replace TileServer-GL with Martin
  martin:
    image: urbica/martin
    container_name: conflict_martin
    restart: unless-stopped
    environment:
      # Use direct password instead of URL encoding which is causing issues
      - "DATABASE_URL=postgres://postgres:Flnqrt5%2678%24%25@db:5432/geo_db"
      - WATCH_MODE=true
      - POOL_SIZE=20
      - KEEP_ALIVE=true
      - WORKER_PROCESSES=4
      - TILE_BUFFER_SIZE=16
      - MAX_AGE=0
    ports:
      - "3001:3000"
    depends_on:
      - db

volumes:
  db-data:
    name: war-data-map_db-data

 